name:                nyf
version:             0.1.0.0
github:              "laluxx/nyf"
license:             MIT
author:              "Laluxx"
maintainer:          "lorenzoaddamo10@gmail.com"
copyright:           "2026 Laluxx"
extra-source-files:
- README.org
- LICENSE
description:         Formatter for the Nytrix programming language

data-files:
- tests/**/*.ny

dependencies:
- base >= 4.7 && < 5
- text
- yaml
- time
- filepath
- directory
- megaparsec
- prettyprinter
- parser-combinators
- aeson
- bytestring
- process
- bytestring
- aeson-pretty

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

executables:
  nyf:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
